package com.andreikingsley.ggdsl.ir.scale

sealed interface DefaultScale: Scale

class UnspecifiedDefaultScale: DefaultScale

sealed interface PositionalDefaultScale: DefaultScale
sealed interface NonPositionalDefaultScale: DefaultScale

class PositionalContinuousDefaultScale: PositionalDefaultScale, ContinuousScale
class PositionalCategoricalDefaultScale: PositionalDefaultScale, CategoricalScale

class NonPositionalContinuousDefaultScale: NonPositionalDefaultScale, ContinuousScale
class NonPositionalCategoricalDefaultScale: NonPositionalDefaultScale, CategoricalScale
