package com.andreikingsley.ggdsl.ir.scale

sealed interface DefaultScale: Scale

class UnspecifiedDefaultScale: DefaultScale
class NonPositionalContinuousDefaultScale: DefaultScale, ContinuousScale
class PositionalContinuousDefaultScale: DefaultScale, ContinuousScale
class NonPositionalCategoricalDefaultScale: DefaultScale, CategoricalScale
class PositionalCategoricalDefaultScale: DefaultScale, CategoricalScale
