package com.andreikingsley.ggdsl.ir.scale

sealed interface DefaultScale: Scale

object UnspecifiedDefaultScale: DefaultScale

sealed interface PositionalDefaultScale: DefaultScale
sealed interface NonPositionalDefaultScale: DefaultScale

object PositionalContinuousDefaultScale: PositionalDefaultScale, ContinuousScale
object PositionalCategoricalDefaultScale: PositionalDefaultScale, CategoricalScale

object NonPositionalContinuousDefaultScale: NonPositionalDefaultScale, ContinuousScale
object NonPositionalCategoricalDefaultScale: NonPositionalDefaultScale, CategoricalScale
